name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      working-directory: jiu-jitsu-notes

    - name: Configure routes
      run: mv routes.production.json routes.json
      working-directory: jiu-jitsu-notes/src/api
    
    - name: Build
      env:
        CI: false
      run: npm run build
      working-directory: jiu-jitsu-notes
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: jiu-jitsu-notes/build
        token: ${{ secrets.GITHUB_TOKEN }}
